name: OPUS 4 Documentation

description: OPUS 4 document repository software user manual

author: Jens Schwidder

author_email: schwidder@zib.de

url: https://opus4.github.io/userdoc

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"


